### ISSUE TITLE
[Request] Aspect Ingredients

### ISSUE THREAD

**Issue by mezz** [Buuz135/Thaumic-JEI#1]
It would be nice to have aspects in the JEI ingredient list, to be able to look up recipes that create those aspects and recipes that use them. I'd explain in more detail but you've already created Villager ingredients in JEI-Villagers so you know what you're doing!

Also feel free to take a look at [JEIAddons](https://github.com/mezz/JEIAddons), which added JEI Thaumcraft compat in 1.8.9. I'm discontinuing it now but the code is MIT so you can use anything you want from it. The JEI API has changed a bit since then but it might still be useful.

**Comment by Buuz135** [comment]
Closed https://github.com/Buuz135/Thaumic-JEI/commit/713b3cbad9aab107e24581b0cc47c514aa453398
