### ISSUE TITLE
[Bug] Aspects from Itemstack caps numbers at 125

### ISSUE THREAD

**Issue by Mike-U5** [Buuz135/Thaumic-JEI#14]
For example, the Automated Crossbow contains **132** metallum.
However, when viewed in the "Aspect from ItemStack" menu, it claims that it only contains a mere **8** metallum.

**Comment by kantenkugel** [comment]
Seeing as this wasn't really fixed with the commit that closed the issue, and me wanting to have it properly display, I created a PR that should now work for aspect counts up to 32k
