### ISSUE TITLE
[1.12.2 Client] Severe slowed Client Loading

### ISSUE THREAD

**Issue by Morpheus1101** [Buuz135/Thaumic-JEI#17]
When starting the client its gets to the point where the below occurs and takes quite a long while significantly slowing down the client loading to 5min+ just in the aspect checking alone.

> 20:54:59] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at x%
[20:55:04] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at x%>

**Comment by Buuz135** [comment]
Impossible it happens in another Thread

**Comment by Morpheus1101** [comment]
This is a snippet for the client im currently loading an waiting to finish loading. https://gist.github.com/Morpheus1101/b58fc727799b182f62d16eb30714d350

**Comment by Buuz135** [comment]
It can't slow down the client thread, because it doesn't happen in the client thread. It doesn't make sense, I have tested it in the pack ATM where the aspect checking takes 17min and the client loads in 6.

**Comment by Morpheus1101** [comment]
With this pack, the client dosent finish loading to be functional until after the Aspect Checking has finished, which takes quite sometime, but if this is intentional then so be it.

**Comment by Buuz135** [comment]
Can I get a screenshot of the client while its waiting?

**Comment by Morpheus1101** [comment]
And now its making a liar out of me lol ... im  just gonna call it gremlins for the last day and say they're now gone as i got no further explanation.
