### ISSUE TITLE
[Question] Aspects from IItemstack without Scanning

### ISSUE THREAD

**Issue by NillerMedDild** [Buuz135/Thaumic-JEI#18]
Hey! Would it be possible to have Aspects from IItemstacks only scan once, and then have it read from the file said scan produces? The scanning makes the game almost unplayable for 5-15minutes the first time I log in after launch.

**Comment by NillerMedDild** [comment]
Damn that was fast, thank you!

**Comment by Buuz135** [comment]
Do you want to know something fasterhttps://minecraft.curseforge.com/projects/thaumic-jei/files/2566912

**Comment by NillerMedDild** [comment]
O_O gj!
