### ISSUE TITLE
Thaumcraft 6 Infusion not working

### ISSUE THREAD

**Issue by Danymaddox** [Buuz135/Thaumic-JEI#2]
Hi! I've instaled Thaumcraft 6 BETA 3 and Thaumic JEI 1.0. There's an incompatibility becaus when I try to make an infusion it does not work. I've tried without Thaumic JEI and it works. Also, I already reported this to the Thaumcraft GitHub and somebudy told me that is problem from Thaumic JEI.

Thanks!

**Comment by Buuz135** [comment]
What recipe?

**Comment by Danymaddox** [comment]
Anyone. The infusion crafting is not working

**Comment by Buuz135** [comment]
Thaumic JEI is a client side mod, it doesn't interact with server side stuff like recipes, and it does work https://imgur.com/o2OnkfS.gifv
