### ISSUE TITLE
"Aspect from ItemStack" tab is weird

### ISSUE THREAD

**Issue by aaronhowser1** [Buuz135/Thaumic-JEI#24]
If you hit U or right click on items in JEI, there's the tab "Aspect from ItemStack" which tells you what aspects that item gives. For some reason, it also tells you what other items give you that aspect too. I think it should just be one page of a list of aspects that are given by the specific item you clicked on, and then you can click on the aspects to see what other items give you that aspect like it does now. It's a bit confusing to look for uses for Cobblestone then see a tab that has like 40 random unrelated items.

**Comment by Buuz135** [comment]
That can't be done, you can't generate recipes depending of what you are looking and I don't want a million recipies
