### ISSUE TITLE
[SUGGESTION] Aspect centrifuge tab

### ISSUE THREAD

**Issue by ST-DDT** [Buuz135/Thaumic-JEI#25]
Its nice that there is a tab for aspect compounds. However it would be nice if you could also add also add a reverse for that. So that it will be easier to trace back how to get "raw" aspects.

**Comment by Buuz135** [comment]
But it is exactly the same, you only need to reverse the mouse clicks you do

**Comment by ST-DDT** [comment]
Ops my bad. (I forgot about that...)
