### ISSUE TITLE
[Bug] Every start ItemStack Aspect Checking

### ISSUE THREAD

**Issue by chaos234** [Buuz135/Thaumic-JEI#28]
Why is there a cache which rechecks every start the ItemStack Aspect? A cache is a long time storage and not to be regenerated every time.

Please remove this or change it, that is fastly checks against changes and create a storage file for every SP/MP map to speed this up because as long as this is running, any connection to a MP server results in a ReadTimeoutException.

If there is nothing, what you can do, I must remove this mod from the entire modpack.

**Comment by QuImUfu** [comment]
Sadly i see no truly reliable way to check for changes that make regen necessary. My pull request https://github.com/Buuz135/Thaumic-JEI/pull/9 (that was never accepted and is now outdated) checked for changes in the mod list and changes in thaumcraft's aspect data at execution time to determine whether it needs to regen the cache, but a mod could (potentially) change the aspect data later, and then Thaumic-JEI would not detect and pick up the change.  
Additionally it is a lot of relatively ugly code (at least the way my pull request was written).

In my opinion the modlist approach with an additional config option (alternatively just delete the cache files) to force regen would be the best solution.

**Comment by Buuz135** [comment]
First of all, there is a config option to disable it. Secondly, you dont need to go threatening me that if I don't change it you will remove it from your pack. Remove it, I don't care, you made your point clear. Thanks for being a kind person today!

Next time try to be nicer to other people.

**Comment by Bjonnfesk** [comment]
> First of all, there is a config option to disable it. Secondly, you dont need to go threatening me that if I don't change it you will remove it from your pack. Remove it, I don't care, you made your point clear. Thanks for being a kind person today!
> 
> Next time try to be nicer to other people.

Come on. He never threatened to do anything, he simply stated he would be forced to remove it.
