### ISSUE TITLE
Bug: Only work for Vanilla Thuamcraft Recipes

### ISSUE THREAD

**Issue by CrankySupertoon01** [Buuz135/Thaumic-JEI#37]
The mod is most likely coded to only show vanilla recipes from thaumcraft. Any addons wont show. What made me think this isnt intentional, is that Arcane Worktable recipes show, but Infusion does not

**Comment by CrankySupertoon01** [comment]
Its been a month i just want to make sure you say this issue report. @Buuz135

**Comment by Buuz135** [comment]
It does work
![java_2018-11-11_15-07-08](https://user-images.githubusercontent.com/3874674/48313990-89ea0980-e5c3-11e8-8800-16dd7d028176.png)
