### ISSUE TITLE
Generating aspect cache kills performance in large mod packs

### ISSUE THREAD

**Issue by Andriamanitra** [Buuz135/Thaumic-JEI#38]
I was having trouble with lag while playing [All The Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3) mod pack so I ran VisualVM to see what was causing it. It appears ThaumicJEI Aspect Cache is eating up insane amounts of CPU time and memory. 

![](https://i.imgur.com/spsia3r.png)

![](https://i.imgur.com/Tdv75CG.png)

![](https://i.imgur.com/QHCF4sP.png)

**Comment by Buuz135** [comment]
That's why there is a config option to disable the check every time you start the game.
