### ISSUE TITLE
Could you please set IRecipeCategory#getIcon for the cauldron recipy category?

### ISSUE THREAD

**Issue by noopynolife** [Buuz135/Thaumic-JEI#4]
I am making an addon that bridges thaumcraft and projecte (I know, hasn't ever been done before lol), and I gave the philosopher stone the ability to do crucible crafting. (crucible from thaumcraft 6)

I then set the philosophers stone as a Recipe Category Crafting Item, which worked, but now the philosophers stone shows up as main crafting item instead of the crucible. Which looks odd.

I asked mezz on the JEI github, and he thinks a solution would be if you'd set IRecipeCategory#getIcon because that always is used first. So is there any chance you could do this? :)

**Comment by Buuz135** [comment]
Will do! 😛

**Comment by noopynolife** [comment]
Thank you!
