### ISSUE TITLE
3x2 Shaped Recipes not transferring correctly

### ISSUE THREAD

**Issue by BrockWS** [Buuz135/Thaumic-JEI#40]
Probably caused by [this code](https://github.com/Buuz135/Thaumic-JEI/blob/eb3f7b363834db557c35030523524207698a974a/src/main/java/com/buuz135/thaumicjei/category/ArcaneWorkbenchCategory.java#L107).

![image](https://user-images.githubusercontent.com/2309747/50548126-ba812200-0c9b-11e9-896e-21a78c221566.png)

![image](https://user-images.githubusercontent.com/2309747/50548135-c7057a80-0c9b-11e9-87f8-0ddd7fc08a3c.png)

**Comment by xJon** [comment]
Fixing this would be appreciated!
