### ISSUE TITLE
Possible Leak

### ISSUE THREAD

**Issue by Anannsul** [Buuz135/Thaumic-JEI#43]
ThamicJEI-1.12.2-1.5.5-23

Okay, first I'd like to say I am a total newbie when it comes to running a modded server.  Second, It is hosted by a company so I don't know if that has an effect on fixes..  But that said...  here we go.

Earlier this week we experienced a pretty bad lag spike, and I started watching the console and noticed a leak was happening...  

22.02 11:10:04 [Server] INFO Feb 22, 2019 11:10:04 AM io.netty.util.ResourceLeakDetector reportUntracedLeak
22.02 11:10:04 [Server] INFO SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

Now i have no clue what that even means or even how to get the report or anything so I was just doing random shit on the server and seeing what was popping up it... I noticed first that it was only being reported once and always after a fresh restart. At first i thought it was another mod because it was popping up when the shapes were being loaded and cached...  but after a while it stopped happening together at the same time...  so no it wasn't that...  back to further pondering and googling at how to deal with the jvm thing.  I kind of figured it out (or honestly thought i did) but when the error happened again today nothing popped up or anything so i went log hunting thinking maybe I was able to do that jvm thing on my own launcher (which i use twitch app so i have no clue what to do and no one seems to have any tutorial out there on stuff like this... aaannnyy way... ) i looked at my log and seen that at the same time the error happened... this was posted:

[11:10:04] [ThaumicJEI Aspect Cache/INFO]: Finished Aspect ItemStack Thread.

I have no clue if the two are even related, and i have no clue how to get the report from the error in the first place for further inspection.  -_- This is so frustrating. lol.  I hope you can help IF this is in fact related to your mod...  if not.. I'm so sorry I made you read this essay of a false report.  D:

**Comment by Buuz135** [comment]
So if you don't have any clue if they are related why you report it to Thaumic Jei. This mod is a client side mod and doesn't run on the server.
