### ISSUE TITLE
Show locked indicator for locked recipes in "all visible" mode

### ISSUE THREAD

**Issue by thePalindrome** [Buuz135/Thaumic-JEI#54]
Some packs (such as FTB Interactions) opt to have all recipes be visible (for understandable reasons such as allowing a decent amount of "look-ahead"), but this leads to trouble with some players not realizing recipes are locked (Alchemical Brass ends up being a particular thorn in our side). It'd be nice to add an indicator (such as crossing out the output or showing a lock icon) in recipes that are currently locked.

**Comment by Saereth** [comment]
Yeah Buuz if there were some indicator on the JEi that they dont have the required research is would be immensely useful
