### ISSUE TITLE
Unlock JEI recipes on research doesn’t work properly.

### ISSUE THREAD

**Issue by SirAron111** [Buuz135/Thaumic-JEI#56]
Unlock JEI recipes on research doesn’t work properly.
So I set it to unlock the recipes in jei once I get the research but that doesn’t work. I did the research for thaumometer and workbench and even infusion but it seems to not unlock them in the JEI. Setting it to always show them works fine.

**Comment by Buuz135** [comment]
Duplicate https://github.com/Buuz135/Thaumic-JEI/issues/34
