### ISSUE TITLE
Aspect from ItemStack not working

### ISSUE THREAD

**Issue by QuImUfu** [Buuz135/Thaumic-JEI#6]
i never got this tab.
```
[19:00:31] [Thread-9/INFO] [ThaumicJEI]: Adding 1219 to the aspect cache
[19:00:31] [Client thread/INFO] [JEI]: Built    recipe registry in 159 ms
[19:00:31] [Client thread/INFO] [JEI]: Building item filter...
[19:00:31] [Thread-9/INFO] [ThaumicJEI]: Cached ItemStack aspects in 551ms
[19:00:31] [Thread-9/INFO] [ThaumicJEI]: Created recipes 0ms
```
Although i get these messages in log that indicate that feature should be working and have finished loading. (if i read your code correctly)
Full Log:
https://paste.ee/p/ubxTO

Tested with:
  Baubles-1.10.2-1.3.13
  jei_1.10.2-3.14.7.420
  Thaumcraft-1.10.2-6.0.BETA7, Thaumcraft-1.10.2-6.0.BETA6 and Thaumcraft-1.10.2-6.0.BETA4
  ThaumicJEI-1.1.1

In all my testruns reproducible.

**Comment by Buuz135** [comment]
That only happens if the game loads too fast but not fast enough to get done inside JEI, I'm not too worried about it as if you add more mods it will make it take more time to cache the aspects and it will work perfectly.

**Comment by QuImUfu** [comment]
What about just adding a sleep period if it does not take long enough?
I (and others for sure) will not use/install more mods.
Adding:
```java
                long waittime = (15000-(System.currentTimeMillis() - time));
                if (waittime>0){
                    try {
                       Thread.sleep(waittime); //pretty inaccurate
                    }catch(InterruptedException e){}
                }
                ThaumicJEI.LOGGER.info("Waited for " + (System.currentTimeMillis() - time) + "ms");
```
after
```java
ThaumicJEI.LOGGER.info("Cached ItemStack aspects in " + (System.currentTimeMillis() - time) + "ms");
```
in ThaumcraftJEIPlugin
is enough to make it work on my PC, probably on all PC's (i mean what crap PC will take longer than 15 secs to load all JEI plugins?) and will not slow loading down for big mod packs.

**Comment by Buuz135** [comment]
Thats a pretty smart way of doing it, I just came up with terrible ways.
