### ISSUE TITLE
Wrong functionality 

### ISSUE THREAD

**Issue by Kitsunyy** [Buuz135/Thaumic-JEI#65]
Hello, Thaumic-jei mod conflicts with the mods on the stages, when an item is added to a stage, it is displayed as if the item is being made on a normal workbench, but it is actually being made in a arcane workbench

![image](https://user-images.githubusercontent.com/56004431/106168183-0b2b1800-619f-11eb-8dd3-485d5f928d1e.png)
![image](https://user-images.githubusercontent.com/56004431/106168213-12522600-619f-11eb-93ce-ae984b25d589.png)

**Comment by Buuz135** [comment]
Not a thaumic jei issue, it doesnt add minecraft recipes. You might be using the staging mod incorrectly.
